# config.py
BINANCE_API_KEY = "PUT YOUR API HERE"
BINANCE_API_SECRET = "PUT YOUR API HERE"

BYBIT_API_KEY = "PUT YOUR API HERE"
BYBIT_API_SECRET = "PUT YOUR API HERE"

OKX_API_KEY = "PUT YOUR API HERE"
OKX_API_SECRET = "PUT YOUR API HERE"
OKX_PASSPHRASE = "PUT YOUR API HERE"
